create table if not exists newsdb
(
    zawartoscID int auto_increment
        primary key,
    tytul       varchar(255) not null,
    data        date         not null,
    zawartosc   text         not null
);

INSERT INTO giganewsdb.newsdb (zawartoscID, tytul, data, zawartosc) VALUES (1, 'Rosjanie otworzyli swój McDonald''s. Wygląda bardzo podobnie ', '2022-06-12', 'W Moskwie i obwodzie moskiewskim rozpoczęły w niedzielę działalność lokale krajowej sieci fastfoodów utworzone na bazie sieci restauracji McDonald''s. Po rosyjskiej inwazji na Ukrainę McDonald''s w maju opuścił Rosję, gdzie działał przez ponad 30 lat. Bary szybkiej obsługi nazywają się "Smacznie - i kropka" (ros. "Wkusno - i toczka"). W menu są frytki, burgery i napoje gazowane. Opakowania są bardzo podobne do poprzednich, tyle że bez charakterystycznych kolorów i loga McDonald''s. Asortyment może się zmienić z powodu wycofywania się zagranicznych dostawców z rynku rosyjskiego. Na razie firma korzysta z zapasów coca-coli, ale będzie szukać zamiennika. "Wzdłuż kolejki stoją pracownicy i rozdają baloniki. Wokół - samochody policyjne, a otwarcie ochraniają funkcjonariusze dwóch specjalnych pułków policji, które wcześniej rozpędzały demonstracje" - relacjonuje niezależna "Nowaja Gazieta", której redakcja działa teraz poza Rosją.');
INSERT INTO giganewsdb.newsdb (zawartoscID, tytul, data, zawartosc) VALUES (2, 'Najdroższa benzyna w historii USA. Niższe ceny mało prawdopodobne ', '2022-06-13', 'Średnia cena galona benzyny w USA po raz pierwszy w historii przekroczyła poziom 5 dol. – podało w sobotę American Automobile Association (AAA). Ceny rosną niemal nieprzerwanie od ponad miesiąca. Jak podaje CNN, sobota jest 15. kolejnym dniem, w którym średnia cena galona (3,78 l) paliwa pobiła dotychczasowe rekordy. Według Biura Statystyk Pracy (BLS), indeks cen benzyny wzrósł w ciągu ostatnich 12 miesięcy o niemal 50 proc., stanowiąc jeden z głównych czynników wpływających na najwyższą od ponad 40 lat inflację.');
INSERT INTO giganewsdb.newsdb (zawartoscID, tytul, data, zawartosc) VALUES (3, 'W tych sklepach Polacy robią zakupy. Raport analityków ', '2022-06-14', 'Polacy coraz częściej robią zakupy, jednocześnie są wobec nich coraz mniej lojalni. W czasach kryzysu wyszukują bowiem promocji. 91 proc. Polaków było w pierwszych osiemnastu tygodniach tego przynajmniej raz w sklepie sieci Biedronka – wynika z raportu firmy technologicznej Proxi.cloud. Sklep Lidla odwiedziło w tym czasie ok. 60 proc. Polaków, Netto – 32 proc., a Aldi – 17 proc. Autorzy raportu wskazali, że klienci częściej niż rok wcześniej robią zakupy w dyskontach. W zeszłym roku w tym samym okresie Biedronkę odwiedziło na przykład 89 proc. – 28 proc. klientów dyskontowych odwiedza takie sklepy co najmniej raz w tygodniu. To oznacza wzrost o 7 punkty procentowe w porównaniu z analogicznym okresem zeszłego roku – podkreśla Mateusz Chołuj z Proxi.cloud. Z analizy wynika jednak, że klienci są coraz mniej lojalni wobec sklepów.');
